variables:
  APP_NAME: eCloud

# Deploy stage
include:
  - project: 'e/infra/ecloud/nextcloud-apps/ci-templates'
    ref: main
    file: 'nc-apps-checkout-deploy.yml'

.deploy:nextcloud-app-by-checkout:
  script:
    - ssh $SSH_USER@$DEPLOYMENT_HOST "git clone --depth 1 $CI_REPOSITORY_URL --branch $DEPLOYMENT_BRANCH --single-branch /tmp/${CI_JOB_ID}/${APP_NAME} && sudo rsync -avzh --chown www-data:www-data --delete --exclude '.git*' /tmp/${CI_JOB_ID}/${eCloud} ${DEPLOYMENT_PATH}/html/themes/ && rm -rf /tmp/${CI_JOB_ID} && docker exec -u www-data $CONTAINER_NAME /usr/local/bin/php /var/www/html/occ maintenance:theme:update"



