stages:
  - deploy

# Deploy stage
include:
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: dev/nc-apps-checkout-deploy
    file: "nc-apps-checkout-deploy.yml"

.deploy:nextcloud-app-by-checkout:
  stage: deploy
  variables:

deploy:production:
  extends: .deploy:nextcloud-app-by-checkout
  when: manual
  only:
    - production
  environment:
    name: prod/01
    url: https://ecloud.global
  variables:
    DEPLOYMENT_BRANCH: $CI_COMMIT_BRANCH
    CONTAINER_NAME: nextcloud
